# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/code-frame-7.16.0" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.16.0.tgz";
        sha512 = "IF4EOMEV+bfYwOmNxGzSnjR2EmQod7f1UXOpZM3l4i4o4QNwzjtJAu/HxdjHq0aYBvdqMuQEY1eg0nqW9ZPORA==";
      };
    };
    "@babel/compat-data-7.16.4" = {
      name = "_at_babel_slash_compat-data";
      packageName = "@babel/compat-data";
      version = "7.16.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/compat-data/-/compat-data-7.16.4.tgz";
        sha512 = "1o/jo7D+kC9ZjHX5v+EHrdjl3PhxMrLSOTGsOdHJ+KL8HCaEK6ehrVL2RS6oHDZp+L7xLirLrPmQtEng769J/Q==";
      };
    };
    "@babel/core-7.16.5" = {
      name = "_at_babel_slash_core";
      packageName = "@babel/core";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/core/-/core-7.16.5.tgz";
        sha512 = "wUcenlLzuWMZ9Zt8S0KmFwGlH6QKRh3vsm/dhDA3CHkiTA45YuG1XkHRcNRl73EFPXDp/d5kVOU0/y7x2w6OaQ==";
      };
    };
    "@babel/generator-7.16.5" = {
      name = "_at_babel_slash_generator";
      packageName = "@babel/generator";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/generator/-/generator-7.16.5.tgz";
        sha512 = "kIvCdjZqcdKqoDbVVdt5R99icaRtrtYhYK/xux5qiWCBmfdvEYMFZ68QCrpE5cbFM1JsuArUNs1ZkuKtTtUcZA==";
      };
    };
    "@babel/helper-annotate-as-pure-7.16.0" = {
      name = "_at_babel_slash_helper-annotate-as-pure";
      packageName = "@babel/helper-annotate-as-pure";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.16.0.tgz";
        sha512 = "ItmYF9vR4zA8cByDocY05o0LGUkp1zhbTQOH1NFyl5xXEqlTJQCEJjieriw+aFpxo16swMxUnUiKS7a/r4vtHg==";
      };
    };
    "@babel/helper-compilation-targets-7.16.3" = {
      name = "_at_babel_slash_helper-compilation-targets";
      packageName = "@babel/helper-compilation-targets";
      version = "7.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-compilation-targets/-/helper-compilation-targets-7.16.3.tgz";
        sha512 = "vKsoSQAyBmxS35JUOOt+07cLc6Nk/2ljLIHwmq2/NM6hdioUaqEXq/S+nXvbvXbZkNDlWOymPanJGOc4CBjSJA==";
      };
    };
    "@babel/helper-environment-visitor-7.16.5" = {
      name = "_at_babel_slash_helper-environment-visitor";
      packageName = "@babel/helper-environment-visitor";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-environment-visitor/-/helper-environment-visitor-7.16.5.tgz";
        sha512 = "ODQyc5AnxmZWm/R2W7fzhamOk1ey8gSguo5SGvF0zcB3uUzRpTRmM/jmLSm9bDMyPlvbyJ+PwPEK0BWIoZ9wjg==";
      };
    };
    "@babel/helper-function-name-7.16.0" = {
      name = "_at_babel_slash_helper-function-name";
      packageName = "@babel/helper-function-name";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-function-name/-/helper-function-name-7.16.0.tgz";
        sha512 = "BZh4mEk1xi2h4HFjWUXRQX5AEx4rvaZxHgax9gcjdLWdkjsY7MKt5p0otjsg5noXw+pB+clMCjw+aEVYADMjog==";
      };
    };
    "@babel/helper-get-function-arity-7.16.0" = {
      name = "_at_babel_slash_helper-get-function-arity";
      packageName = "@babel/helper-get-function-arity";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-get-function-arity/-/helper-get-function-arity-7.16.0.tgz";
        sha512 = "ASCquNcywC1NkYh/z7Cgp3w31YW8aojjYIlNg4VeJiHkqyP4AzIvr4qx7pYDb4/s8YcsZWqqOSxgkvjUz1kpDQ==";
      };
    };
    "@babel/helper-hoist-variables-7.16.0" = {
      name = "_at_babel_slash_helper-hoist-variables";
      packageName = "@babel/helper-hoist-variables";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-hoist-variables/-/helper-hoist-variables-7.16.0.tgz";
        sha512 = "1AZlpazjUR0EQZQv3sgRNfM9mEVWPK3M6vlalczA+EECcPz3XPh6VplbErL5UoMpChhSck5wAJHthlj1bYpcmg==";
      };
    };
    "@babel/helper-module-imports-7.16.0" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.16.0.tgz";
        sha512 = "kkH7sWzKPq0xt3H1n+ghb4xEMP8k0U7XV3kkB+ZGy69kDk2ySFW1qPi06sjKzFY3t1j6XbJSqr4mF9L7CYVyhg==";
      };
    };
    "@babel/helper-module-transforms-7.16.5" = {
      name = "_at_babel_slash_helper-module-transforms";
      packageName = "@babel/helper-module-transforms";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.16.5.tgz";
        sha512 = "CkvMxgV4ZyyioElFwcuWnDCcNIeyqTkCm9BxXZi73RR1ozqlpboqsbGUNvRTflgZtFbbJ1v5Emvm+lkjMYY/LQ==";
      };
    };
    "@babel/helper-plugin-utils-7.16.5" = {
      name = "_at_babel_slash_helper-plugin-utils";
      packageName = "@babel/helper-plugin-utils";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-plugin-utils/-/helper-plugin-utils-7.16.5.tgz";
        sha512 = "59KHWHXxVA9K4HNF4sbHCf+eJeFe0Te/ZFGqBT4OjXhrwvA04sGfaEGsVTdsjoszq0YTP49RC9UKe5g8uN2RwQ==";
      };
    };
    "@babel/helper-simple-access-7.16.0" = {
      name = "_at_babel_slash_helper-simple-access";
      packageName = "@babel/helper-simple-access";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-simple-access/-/helper-simple-access-7.16.0.tgz";
        sha512 = "o1rjBT/gppAqKsYfUdfHq5Rk03lMQrkPHG1OWzHWpLgVXRH4HnMM9Et9CVdIqwkCQlobnGHEJMsgWP/jE1zUiw==";
      };
    };
    "@babel/helper-split-export-declaration-7.16.0" = {
      name = "_at_babel_slash_helper-split-export-declaration";
      packageName = "@babel/helper-split-export-declaration";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-split-export-declaration/-/helper-split-export-declaration-7.16.0.tgz";
        sha512 = "0YMMRpuDFNGTHNRiiqJX19GjNXA4H0E8jZ2ibccfSxaCogbm3am5WN/2nQNj0YnQwGWM1J06GOcQ2qnh3+0paw==";
      };
    };
    "@babel/helper-validator-identifier-7.15.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.15.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.15.7.tgz";
        sha512 = "K4JvCtQqad9OY2+yTU8w+E82ywk/fe+ELNlt1G8z3bVGlZfn/hOcQQsUhGhW/N+tb3fxK800wLtKOE/aM0m72w==";
      };
    };
    "@babel/helper-validator-option-7.14.5" = {
      name = "_at_babel_slash_helper-validator-option";
      packageName = "@babel/helper-validator-option";
      version = "7.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-option/-/helper-validator-option-7.14.5.tgz";
        sha512 = "OX8D5eeX4XwcroVW45NMvoYaIuFI+GQpA2a8Gi+X/U/cDUIRsV37qQfF905F0htTRCREQIB4KqPeaveRJUl3Ow==";
      };
    };
    "@babel/helpers-7.16.5" = {
      name = "_at_babel_slash_helpers";
      packageName = "@babel/helpers";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helpers/-/helpers-7.16.5.tgz";
        sha512 = "TLgi6Lh71vvMZGEkFuIxzaPsyeYCHQ5jJOOX1f0xXn0uciFuE8cEk0wyBquMcCxBXZ5BJhE2aUB7pnWTD150Tw==";
      };
    };
    "@babel/highlight-7.16.0" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.16.0.tgz";
        sha512 = "t8MH41kUQylBtu2+4IQA3atqevA2lRgqA2wyVB/YiWmsDSuylZZuXOUy9ric30hfzauEFfdsuk/eXTRrGrfd0g==";
      };
    };
    "@babel/parser-7.16.6" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.16.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.16.6.tgz";
        sha512 = "Gr86ujcNuPDnNOY8mi383Hvi8IYrJVJYuf3XcuBM/Dgd+bINn/7tHqsj+tKkoreMbmGsFLsltI/JJd8fOFWGDQ==";
      };
    };
    "@babel/plugin-syntax-jsx-7.16.5" = {
      name = "_at_babel_slash_plugin-syntax-jsx";
      packageName = "@babel/plugin-syntax-jsx";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-syntax-jsx/-/plugin-syntax-jsx-7.16.5.tgz";
        sha512 = "42OGssv9NPk4QHKVgIHlzeLgPOW5rGgfV5jzG90AhcXXIv6hu/eqj63w4VgvRxdvZY3AlYeDgPiSJ3BqAd1Y6Q==";
      };
    };
    "@babel/plugin-transform-react-jsx-7.16.5" = {
      name = "_at_babel_slash_plugin-transform-react-jsx";
      packageName = "@babel/plugin-transform-react-jsx";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx/-/plugin-transform-react-jsx-7.16.5.tgz";
        sha512 = "+arLIz1d7kmwX0fKxTxbnoeG85ONSnLpvdODa4P3pc1sS7CV1hfmtYWufkW/oYsPnkDrEeQFxhUWcFnrXW7jQQ==";
      };
    };
    "@babel/plugin-transform-react-jsx-development-7.16.5" = {
      name = "_at_babel_slash_plugin-transform-react-jsx-development";
      packageName = "@babel/plugin-transform-react-jsx-development";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx-development/-/plugin-transform-react-jsx-development-7.16.5.tgz";
        sha512 = "uQSLacMZSGLCxOw20dzo1dmLlKkd+DsayoV54q3MHXhbqgPzoiGerZQgNPl/Ro8/OcXV2ugfnkx+rxdS0sN5Uw==";
      };
    };
    "@babel/plugin-transform-react-jsx-self-7.16.5" = {
      name = "_at_babel_slash_plugin-transform-react-jsx-self";
      packageName = "@babel/plugin-transform-react-jsx-self";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx-self/-/plugin-transform-react-jsx-self-7.16.5.tgz";
        sha512 = "fvwq+jir1Vn4f5oBS0H/J/gD5CneTD53MHs+NMjlHcha4Sq35fwxI5RtmJGEBXO+M93f/eeD9cAhRPhmLyJiVw==";
      };
    };
    "@babel/plugin-transform-react-jsx-source-7.16.5" = {
      name = "_at_babel_slash_plugin-transform-react-jsx-source";
      packageName = "@babel/plugin-transform-react-jsx-source";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx-source/-/plugin-transform-react-jsx-source-7.16.5.tgz";
        sha512 = "/eP+nZywJntGLjSPjksAnM9/ELIs3RbiEuTu2/zAOzwwBcfiu+m/iptEq1lERUUtSXubYSHVnVHMr13GR+TwPw==";
      };
    };
    "@babel/runtime-7.16.5" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.16.5.tgz";
        sha512 = "TXWihFIS3Pyv5hzR7j6ihmeLkZfrXGxAr5UfSl8CHf+6q/wpiYDkUau0czckpYG8QmnCIuPpdLtuA9VmuGGyMA==";
      };
    };
    "@babel/template-7.16.0" = {
      name = "_at_babel_slash_template";
      packageName = "@babel/template";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/template/-/template-7.16.0.tgz";
        sha512 = "MnZdpFD/ZdYhXwiunMqqgyZyucaYsbL0IrjoGjaVhGilz+x8YB++kRfygSOIj1yOtWKPlx7NBp+9I1RQSgsd5A==";
      };
    };
    "@babel/traverse-7.16.5" = {
      name = "_at_babel_slash_traverse";
      packageName = "@babel/traverse";
      version = "7.16.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/traverse/-/traverse-7.16.5.tgz";
        sha512 = "FOCODAzqUMROikDYLYxl4nmwiLlu85rNqBML/A5hKRVXG2LV8d0iMqgPzdYTcIpjZEBB7D6UDU9vxRZiriASdQ==";
      };
    };
    "@babel/types-7.16.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.16.0.tgz";
        sha512 = "PJgg/k3SdLsGb3hhisFvtLOw5ts113klrpLuIPtCJIU+BB24fqq6lf8RWqKJEjzqXR9AEH1rIb5XTqwBHB+kQg==";
      };
    };
    "@rollup/pluginutils-4.1.2" = {
      name = "_at_rollup_slash_pluginutils";
      packageName = "@rollup/pluginutils";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-4.1.2.tgz";
        sha512 = "ROn4qvkxP9SyPeHaf7uQC/GPFY6L/OWy9+bd9AwcjOAWQwxRscoEyAUD8qCY5o5iL4jqQwoLk2kaTKJPb/HwzQ==";
      };
    };
    "@types/node-17.0.8" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.8.tgz";
        sha512 = "YofkM6fGv4gDJq78g4j0mMuGMkZVxZDgtU0JRdx6FgiJDG+0fY0GKVolOV8WqVmEhLCXkQRjwDdKyPxJp/uucg==";
      };
    };
    "@types/prop-types-15.7.4" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.4.tgz";
        sha512 = "rZ5drC/jWjrArrS8BR6SIr4cWpW09RNTYt9AMZo3Jwwif+iacXAqgVjm0B0Bv/S1jhDXKHqRVNCbACkJ89RAnQ==";
      };
    };
    "@types/react-17.0.38" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "17.0.38";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-17.0.38.tgz";
        sha512 = "SI92X1IA+FMnP3qM5m4QReluXzhcmovhZnLNm3pyeQlooi02qI7sLiepEYqT678uNiyc25XfCqxREFpy3W7YhQ==";
      };
    };
    "@types/react-dom-17.0.11" = {
      name = "_at_types_slash_react-dom";
      packageName = "@types/react-dom";
      version = "17.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-dom/-/react-dom-17.0.11.tgz";
        sha512 = "f96K3k+24RaLGVu/Y2Ng3e1EbZ8/cVJvypZWd7cy0ofCBaf2lcM46xNhycMZ2xGwbBjRql7hOlZ+e2WlJ5MH3Q==";
      };
    };
    "@types/scheduler-0.16.2" = {
      name = "_at_types_slash_scheduler";
      packageName = "@types/scheduler";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/scheduler/-/scheduler-0.16.2.tgz";
        sha512 = "hppQEBDmlwhFAXKJX2KnWLYu5yMfi91yazPb2l+lbJiwW+wdo1gNeRA+3RgNSO39WYX2euey41KEwnqesU2Jew==";
      };
    };
    "@types/uuid-8.3.4" = {
      name = "_at_types_slash_uuid";
      packageName = "@types/uuid";
      version = "8.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/uuid/-/uuid-8.3.4.tgz";
        sha512 = "c/I8ZRb51j+pYGAu5CrFMRxqZ2ke4y2grEBO5AUjgSkSk+qT2Ea+OdWElz/OiMf5MNpn2b17kuVBwZLQJXzihw==";
      };
    };
    "@vitejs/plugin-react-1.1.3" = {
      name = "_at_vitejs_slash_plugin-react";
      packageName = "@vitejs/plugin-react";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vitejs/plugin-react/-/plugin-react-1.1.3.tgz";
        sha512 = "xv8QujX/uR4ti8qpt0hMriM2bdpxX4jm4iU6GAZfCwHjh/ewkX/8DJgnmQpE0HSJmgz8dixyUnRJKi2Pf1nNoQ==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "browserslist-4.19.1" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.19.1.tgz";
        sha512 = "u2tbbG5PdKRTUoctO3NBD8FQ5HdPh1ZXPHzp1rwaa5jTc+RV9/+RlWiAIKmjRPQF+xbGM9Kklj5bZQFa2s/38A==";
      };
    };
    "caniuse-lite-1.0.30001292" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001292";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001292.tgz";
        sha512 = "jnT4Tq0Q4ma+6nncYQVe7d73kmDmE9C3OGTx3MvW7lBM/eY1S1DZTMBON7dqV481RhNiS5OxD7k9JQvmDOTirw==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "convert-source-map-1.8.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.8.0.tgz";
        sha512 = "+OQdjP49zViI/6i7nIJpA8rAl4sV/JdPfU9nZs3VqOwGIgizICvuN2ru6fMd+4llL0tar18UYJXfZ/TWtmhUjA==";
      };
    };
    "csstype-3.0.10" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.0.10.tgz";
        sha512 = "2u44ZG2OcNUO9HDp/Jl8C07x6pU/eTR3ncV91SiK3dhG9TWvRVsCoJw14Ckx5DgWkzGA3waZWO3d7pgqpUI/XA==";
      };
    };
    "debug-4.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.3.tgz";
        sha512 = "/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q==";
      };
    };
    "electron-to-chromium-1.4.28" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.28.tgz";
        sha512 = "Gzbf0wUtKfyPaqf0Plz+Ctinf9eQIzxEqBHwSvbGfeOm9GMNdLxyu1dNiCUfM+x6r4BE0xUJNh3Nmg9gfAtTmg==";
      };
    };
    "esbuild-0.13.15" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.13.15.tgz";
        sha512 = "raCxt02HBKv8RJxE8vkTSCXGIyKHdEdGfUmiYb8wnabnaEmHzyW7DCHb5tEN0xU8ryqg5xw54mcwnYkC4x3AIw==";
      };
    };
    "esbuild-android-arm64-0.13.15" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.13.15.tgz";
        sha512 = "m602nft/XXeO8YQPUDVoHfjyRVPdPgjyyXOxZ44MK/agewFFkPa8tUo6lAzSWh5Ui5PB4KR9UIFTSBKh/RrCmg==";
      };
    };
    "esbuild-darwin-64-0.13.15" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.13.15.tgz";
        sha512 = "ihOQRGs2yyp7t5bArCwnvn2Atr6X4axqPpEdCFPVp7iUj4cVSdisgvEKdNR7yH3JDjW6aQDw40iQFoTqejqxvQ==";
      };
    };
    "esbuild-darwin-arm64-0.13.15" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.13.15.tgz";
        sha512 = "i1FZssTVxUqNlJ6cBTj5YQj4imWy3m49RZRnHhLpefFIh0To05ow9DTrXROTE1urGTQCloFUXTX8QfGJy1P8dQ==";
      };
    };
    "esbuild-freebsd-64-0.13.15" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.13.15.tgz";
        sha512 = "G3dLBXUI6lC6Z09/x+WtXBXbOYQZ0E8TDBqvn7aMaOCzryJs8LyVXKY4CPnHFXZAbSwkCbqiPuSQ1+HhrNk7EA==";
      };
    };
    "esbuild-freebsd-arm64-0.13.15" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.13.15.tgz";
        sha512 = "KJx0fzEDf1uhNOZQStV4ujg30WlnwqUASaGSFPhznLM/bbheu9HhqZ6mJJZM32lkyfGJikw0jg7v3S0oAvtvQQ==";
      };
    };
    "esbuild-linux-32-0.13.15" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.13.15.tgz";
        sha512 = "ZvTBPk0YWCLMCXiFmD5EUtB30zIPvC5Itxz0mdTu/xZBbbHJftQgLWY49wEPSn2T/TxahYCRDWun5smRa0Tu+g==";
      };
    };
    "esbuild-linux-64-0.13.15" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.13.15.tgz";
        sha512 = "eCKzkNSLywNeQTRBxJRQ0jxRCl2YWdMB3+PkWFo2BBQYC5mISLIVIjThNtn6HUNqua1pnvgP5xX0nHbZbPj5oA==";
      };
    };
    "esbuild-linux-arm-0.13.15" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.13.15.tgz";
        sha512 = "wUHttDi/ol0tD8ZgUMDH8Ef7IbDX+/UsWJOXaAyTdkT7Yy9ZBqPg8bgB/Dn3CZ9SBpNieozrPRHm0BGww7W/jA==";
      };
    };
    "esbuild-linux-arm64-0.13.15" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.13.15.tgz";
        sha512 = "bYpuUlN6qYU9slzr/ltyLTR9YTBS7qUDymO8SV7kjeNext61OdmqFAzuVZom+OLW1HPHseBfJ/JfdSlx8oTUoA==";
      };
    };
    "esbuild-linux-mips64le-0.13.15" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.13.15.tgz";
        sha512 = "KlVjIG828uFPyJkO/8gKwy9RbXhCEUeFsCGOJBepUlpa7G8/SeZgncUEz/tOOUJTcWMTmFMtdd3GElGyAtbSWg==";
      };
    };
    "esbuild-linux-ppc64le-0.13.15" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.13.15.tgz";
        sha512 = "h6gYF+OsaqEuBjeesTBtUPw0bmiDu7eAeuc2OEH9S6mV9/jPhPdhOWzdeshb0BskRZxPhxPOjqZ+/OqLcxQwEQ==";
      };
    };
    "esbuild-netbsd-64-0.13.15" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.13.15.tgz";
        sha512 = "3+yE9emwoevLMyvu+iR3rsa+Xwhie7ZEHMGDQ6dkqP/ndFzRHkobHUKTe+NCApSqG5ce2z4rFu+NX/UHnxlh3w==";
      };
    };
    "esbuild-openbsd-64-0.13.15" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.13.15.tgz";
        sha512 = "wTfvtwYJYAFL1fSs8yHIdf5GEE4NkbtbXtjLWjM3Cw8mmQKqsg8kTiqJ9NJQe5NX/5Qlo7Xd9r1yKMMkHllp5g==";
      };
    };
    "esbuild-sunos-64-0.13.15" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.13.15.tgz";
        sha512 = "lbivT9Bx3t1iWWrSnGyBP9ODriEvWDRiweAs69vI+miJoeKwHWOComSRukttbuzjZ8r1q0mQJ8Z7yUsDJ3hKdw==";
      };
    };
    "esbuild-windows-32-0.13.15" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.13.15.tgz";
        sha512 = "fDMEf2g3SsJ599MBr50cY5ve5lP1wyVwTe6aLJsM01KtxyKkB4UT+fc5MXQFn3RLrAIAZOG+tHC+yXObpSn7Nw==";
      };
    };
    "esbuild-windows-64-0.13.15" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.13.15.tgz";
        sha512 = "9aMsPRGDWCd3bGjUIKG/ZOJPKsiztlxl/Q3C1XDswO6eNX/Jtwu4M+jb6YDH9hRSUflQWX0XKAfWzgy5Wk54JQ==";
      };
    };
    "esbuild-windows-arm64-0.13.15" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.13.15.tgz";
        sha512 = "zzvyCVVpbwQQATaf3IG8mu1IwGEiDxKkYUdA4FpoCHi1KtPa13jeScYDjlW0Qh+ebWzpKfR2ZwvqAQkSWNcKjA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gensync-1.0.0-beta.2" = {
      name = "gensync";
      packageName = "gensync";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensync/-/gensync-1.0.0-beta.2.tgz";
        sha512 = "3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
      };
    };
    "globals-11.12.0" = {
      name = "globals";
      packageName = "globals";
      version = "11.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-11.12.0.tgz";
        sha512 = "WOBp/EEGUiIsJSp7wcv/y6MO+lV9UoncWqxuFfm8eBwzWNgyfBd6Gz+IeKQ9jCmyhoH99g15M3T+QaVHFjizVA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "history-5.2.0" = {
      name = "history";
      packageName = "history";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-5.2.0.tgz";
        sha512 = "uPSF6lAJb3nSePJ43hN3eKj1dTWpN9gMod0ZssbFTIsen+WehTmEadgL+kg78xLJFdRfrrC//SavDzmRVdE+Ig==";
      };
    };
    "is-core-module-2.8.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.8.0.tgz";
        sha512 = "vd15qHsaqrRL7dtH6QNuy0ndJmRDrS9HAM1CAiSifNUFv4x1a0CCVsj18hJ1mShxIG6T2i1sO78MkP56r0nYRw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsesc-2.5.2" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-2.5.2.tgz";
        sha512 = "OYu7XEzjkCQ3C5Ps3QIZsQfNpqoJyZZA99wd9aWd05NCtC5pWOkShK2mkL6HXQR6/Cy2lbNdPlZBpuQHXE63gA==";
      };
    };
    "json5-2.2.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.0.tgz";
        sha512 = "f+8cldu7X/y7RAJurMEJmdoKXGB/X550w2Nr3tTbezL6RwEE/iMcm+tZnXeoZtKuOq6ft8+CqzEkrIgx1fPoQA==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nanoid-3.1.30" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.1.30.tgz";
        sha512 = "zJpuPDwOv8D2zq2WRoMe1HsfZthVewpel9CAvTfc/2mBD1uUT/agc5f7GHGWXlYkFvi1mVxe4IjvP2HNrop7nQ==";
      };
    };
    "node-releases-2.0.1" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.1.tgz";
        sha512 = "CqyzN6z7Q6aMeF/ktcMVTzhAHCEpf8SOarwpzpf8pNBY2k5/oM34UHldUwp8VKI7uxct2HxSRdJjBaZeESzcxA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.0" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.0.tgz";
        sha512 = "lY1Q/PiJGC2zOv/z391WOTD+Z02bCgsFfvxoXXf6h7kv9o+WmsmzYqrAwY63sNgOxE4xEdq0WyUnXfKeBrSvYw==";
      };
    };
    "postcss-8.4.5" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.5.tgz";
        sha512 = "jBDboWM8qpaqwkMwItqTQTiFikhs/67OYVvblFFTM7MrZjt6yMKd6r2kgXizEbTTljacm4NldIlZnhbjr84QYg==";
      };
    };
    "react-17.0.2" = {
      name = "react";
      packageName = "react";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-17.0.2.tgz";
        sha512 = "gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==";
      };
    };
    "react-dom-17.0.2" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-17.0.2.tgz";
        sha512 = "s4h96KtLDUQlsENhMn1ar8t2bEa+q/YAtj8pPPdIjPDGBDIVNsrD9aXNWqspUe6AzKCIG0C1HZZLqLV7qpOBGA==";
      };
    };
    "react-refresh-0.11.0" = {
      name = "react-refresh";
      packageName = "react-refresh";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-refresh/-/react-refresh-0.11.0.tgz";
        sha512 = "F27qZr8uUqwhWZboondsPx8tnC3Ct3SxZA3V5WyEvujRyyNv0VYPhoBg1gZ8/MV5tubQp76Trw8lTv9hzRBa+A==";
      };
    };
    "react-router-6.2.1" = {
      name = "react-router";
      packageName = "react-router";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-6.2.1.tgz";
        sha512 = "2fG0udBtxou9lXtK97eJeET2ki5//UWfQSl1rlJ7quwe6jrktK9FCCc8dQb5QY6jAv3jua8bBQRhhDOM/kVRsg==";
      };
    };
    "react-router-dom-6.2.1" = {
      name = "react-router-dom";
      packageName = "react-router-dom";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-6.2.1.tgz";
        sha512 = "I6Zax+/TH/cZMDpj3/4Fl2eaNdcvoxxHoH1tYOREsQ22OKDYofGebrNm6CTPUcvLvZm63NL/vzCYdjf9CUhqmA==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "resolve-1.20.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz";
        sha512 = "wENBPt4ySzg4ybFQW2TT1zMQucPK95HSh/nq2CFTZVOGut2+pQvSsgtda4d26YrYcr067wjbmzOG8byDPBX63A==";
      };
    };
    "rollup-2.62.0" = {
      name = "rollup";
      packageName = "rollup";
      version = "2.62.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-2.62.0.tgz";
        sha512 = "cJEQq2gwB0GWMD3rYImefQTSjrPYaC6s4J9pYqnstVLJ1CHa/aZNVkD4Epuvg4iLeMA4KRiq7UM7awKK6j7jcw==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "scheduler-0.20.2" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.20.2.tgz";
        sha512 = "2eWfGgAqqWFGqtdMmcL5zCMK1U8KlXv8SQFGglL3CEtd0aDVDWgeF/YoCmvln55m5zSk3J/20hTaSBeSObsQDQ==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-js-1.0.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.1.tgz";
        sha512 = "4+TN2b3tqOCd/kaGRJ/sTYA0tR0mdXx26ipdolxcwtJVqEnqNYvlCAt1q3ypy4QMlYus+Zh34RNtYLoq2oQ4IA==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "typescript-4.5.4" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.5.4.tgz";
        sha512 = "VgYs2A2QIRuGphtzFV7aQJduJ2gyfTljngLzjpfW9FoYZF6xuw1W0vW9ghCKLfcWrCFxK81CSGRAvS1pn4fIUg==";
      };
    };
    "uuid-8.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz";
        sha512 = "+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==";
      };
    };
    "vite-2.7.7" = {
      name = "vite";
      packageName = "vite";
      version = "2.7.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite/-/vite-2.7.7.tgz";
        sha512 = "Nm4ingl//gMSj/p1aCBHuTc5Fd8W8Mwdci/HUvqCVq8xaJqF7z08S/LRq1M9kS0jRfJk1/f/CwUyQAr6YgsOLw==";
      };
    };
  };
  args = {
    name = "xchg";
    packageName = "xchg";
    version = "0.0.0";
    src = ./..;
    dependencies = [
      sources."@babel/code-frame-7.16.0"
      sources."@babel/compat-data-7.16.4"
      sources."@babel/core-7.16.5"
      sources."@babel/generator-7.16.5"
      sources."@babel/helper-annotate-as-pure-7.16.0"
      sources."@babel/helper-compilation-targets-7.16.3"
      sources."@babel/helper-environment-visitor-7.16.5"
      sources."@babel/helper-function-name-7.16.0"
      sources."@babel/helper-get-function-arity-7.16.0"
      sources."@babel/helper-hoist-variables-7.16.0"
      sources."@babel/helper-module-imports-7.16.0"
      sources."@babel/helper-module-transforms-7.16.5"
      sources."@babel/helper-plugin-utils-7.16.5"
      sources."@babel/helper-simple-access-7.16.0"
      sources."@babel/helper-split-export-declaration-7.16.0"
      sources."@babel/helper-validator-identifier-7.15.7"
      sources."@babel/helper-validator-option-7.14.5"
      sources."@babel/helpers-7.16.5"
      sources."@babel/highlight-7.16.0"
      sources."@babel/parser-7.16.6"
      sources."@babel/plugin-syntax-jsx-7.16.5"
      sources."@babel/plugin-transform-react-jsx-7.16.5"
      sources."@babel/plugin-transform-react-jsx-development-7.16.5"
      sources."@babel/plugin-transform-react-jsx-self-7.16.5"
      sources."@babel/plugin-transform-react-jsx-source-7.16.5"
      sources."@babel/runtime-7.16.5"
      sources."@babel/template-7.16.0"
      sources."@babel/traverse-7.16.5"
      sources."@babel/types-7.16.0"
      sources."@rollup/pluginutils-4.1.2"
      sources."@types/node-17.0.8"
      sources."@types/prop-types-15.7.4"
      sources."@types/react-17.0.38"
      sources."@types/react-dom-17.0.11"
      sources."@types/scheduler-0.16.2"
      sources."@types/uuid-8.3.4"
      sources."@vitejs/plugin-react-1.1.3"
      sources."ansi-styles-3.2.1"
      sources."browserslist-4.19.1"
      sources."caniuse-lite-1.0.30001292"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."convert-source-map-1.8.0"
      sources."csstype-3.0.10"
      sources."debug-4.3.3"
      sources."electron-to-chromium-1.4.28"
      sources."esbuild-0.13.15"
      sources."esbuild-android-arm64-0.13.15"
      sources."esbuild-darwin-64-0.13.15"
      sources."esbuild-darwin-arm64-0.13.15"
      sources."esbuild-freebsd-64-0.13.15"
      sources."esbuild-freebsd-arm64-0.13.15"
      sources."esbuild-linux-32-0.13.15"
      sources."esbuild-linux-64-0.13.15"
      sources."esbuild-linux-arm-0.13.15"
      sources."esbuild-linux-arm64-0.13.15"
      sources."esbuild-linux-mips64le-0.13.15"
      sources."esbuild-linux-ppc64le-0.13.15"
      sources."esbuild-netbsd-64-0.13.15"
      sources."esbuild-openbsd-64-0.13.15"
      sources."esbuild-sunos-64-0.13.15"
      sources."esbuild-windows-32-0.13.15"
      sources."esbuild-windows-64-0.13.15"
      sources."esbuild-windows-arm64-0.13.15"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."estree-walker-2.0.2"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."gensync-1.0.0-beta.2"
      sources."globals-11.12.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."history-5.2.0"
      sources."is-core-module-2.8.0"
      sources."js-tokens-4.0.0"
      sources."jsesc-2.5.2"
      sources."json5-2.2.0"
      sources."loose-envify-1.4.0"
      sources."minimist-1.2.5"
      sources."ms-2.1.2"
      sources."nanoid-3.1.30"
      sources."node-releases-2.0.1"
      sources."object-assign-4.1.1"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.0"
      sources."postcss-8.4.5"
      sources."react-17.0.2"
      sources."react-dom-17.0.2"
      sources."react-refresh-0.11.0"
      sources."react-router-6.2.1"
      sources."react-router-dom-6.2.1"
      sources."regenerator-runtime-0.13.9"
      sources."resolve-1.20.0"
      sources."rollup-2.62.0"
      sources."safe-buffer-5.1.2"
      sources."scheduler-0.20.2"
      sources."semver-6.3.0"
      sources."source-map-0.5.7"
      sources."source-map-js-1.0.1"
      sources."supports-color-5.5.0"
      sources."to-fast-properties-2.0.0"
      sources."typescript-4.5.4"
      sources."uuid-8.3.2"
      sources."vite-2.7.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
