name: rtcp-server
version: '0.1.0.0'
dependencies:
  - base == 4.*
  - aeson
  - bytestring
  - clientsession
  - cookie
  - containers
  - cryptonite
  - http-client
  - http-client-tls
  - http-types
  - memory
  - oidc-client
  - optparse-applicative
  - random
  - text
  - time
  - uuid
  - vault
  - wai
  - wai-extra
  - wai-middleware-static
  - wai-websockets
  - warp
  - websockets
executables:
  rtcp-server:
    main: Main.hs
    other-modules:
      - Auth
      - Log
      - Messages
    default-extensions:
      - LambdaCase
      - OverloadedStrings
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
