name: rtcp-server
version: '0.1.0.0'
dependencies:
  - base == 4.*
  - aeson
  - bytestring
  - clientsession
  - containers
  - http-types
  - optparse-applicative
  - random
  - text
  - uuid
  - wai
  - wai-extra
  - wai-middleware-static
  - wai-websockets
  - warp
  - websockets
executables:
  rtcp-server:
    main: Main.hs
    other-modules:
      - Log
      - Messages
    default-extensions:
      - LambdaCase
      - OverloadedStrings
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
