dependencies:
  - base == 4.*
  - aeson
  - http-types
  - random
  - text
  - wai
  - wai-extra
  - wai-middleware-static
  - wai-websockets
  - warp
  - websockets
executables:
  xchg-server:
    main: Main.hs
